from abc import ABC, abstractmethod
from collections.abc import Iterable, Iterator
from concurrent.futures import ThreadPoolExecutor, as_completed
from itertools import chain

import polars as pl
from tqdm.auto import tqdm

from fedaugment.types import FloatArray, StrArray


class PromptStrategy(ABC):
    """Abstract base class for prompting strategies."""

    def __init__(self, alias: str) -> None:
        super().__init__()
        self.alias = alias

    def generate_prompts(
        self,
        tables: Iterable[tuple[str, pl.DataFrame]],
        n_tables: int | None = None,
        n_workers: int | None = None,
    ) -> tuple[list[str], list[str]]:
        """Generate prompts from a collection of tables.

        Args:
            tables: An iterator of tuples containing table names and their corresponding DataFrame.
            n_tables: The number of tables to process (only used for the progress bar).
            n_workers: The number of workers to use for parallel processing. If None, it defaults
                to the number of available CPU cores.

        Returns:
            A tuple with two lists containing the generated prompt IDs and prompts.
        """
        prompt_iter: Iterable[tuple[list[str], list[str]]]
        if n_workers is None or n_workers > 1:
            prompt_iter = self._generate_prompts_parallel(tables, n_tables, n_workers)
        else:
            prompt_iter = tqdm(
                (self._generate_prompts_from_table(table) for table in tables),
                desc="Generating prompts",
                total=n_tables,
                leave=False,
                unit="table",
                mininterval=1.0,
                dynamic_ncols=True,
            )

        ids, prompts = zip(*prompt_iter, strict=True)
        return list(chain.from_iterable(ids)), list(chain.from_iterable(prompts))

    def _generate_prompts_parallel(
        self,
        tables: Iterable[tuple[str, pl.DataFrame]],
        n_tables: int | None = None,
        n_workers: int | None = None,
    ) -> Iterator[tuple[list[str], list[str]]]:
        """Generate prompts from a collection of tables in parallel."""
        with (
            tqdm(
                desc="Generating prompts",
                total=n_tables,
                leave=False,
                unit="table",
                mininterval=1.0,
                dynamic_ncols=True,
            ) as pbar,
            ThreadPoolExecutor(max_workers=n_workers) as executor,
        ):
            futures = [
                executor.submit(self._generate_prompts_from_table, table) for table in tables
            ]
            for future in futures:
                future.add_done_callback(lambda _: pbar.update(1))
            for future in as_completed(futures):
                yield future.result()

    @abstractmethod
    def _generate_prompts_from_table(
        self, table: tuple[str, pl.DataFrame]
    ) -> tuple[list[str], list[str]]:
        """Generate prompts from a single table.

        Args:
            table: A tuple containing the table name and its corresponding DataFrame.

        Returns:
            A tuple with two lists containing the generated prompt IDs and prompts.
        """

    @abstractmethod
    def process_embeddings(
        self, prompt_ids: list[str], embeddings: FloatArray
    ) -> tuple[StrArray, FloatArray]:
        """Post-process embeddings produced for prompts generated by this strategy.

        This method must sort the prompt IDs as the prompts may have been processed out of order.

        Args:
            prompt_ids: A sequence of prompt IDs.
            embeddings: A (N, D) array with the embedding per prompt, where N is the number of
                prompts and D is the embedding dimension.

        Returns:
            A tuple containing:
                - The sorted list of column IDs corresponding to the table collection used in
                    generate_prompts() as a Numpy string array.
                - A (N, D) array of embeddings, where N is the number of columns and D is the
                    embedding dimension.
        """
